### ISSUE TITLE
Update user post count when importing topics and posts (replies)

### ISSUE THREAD

**Issue by ilix** [vimla-se/lithium-nodebb-migrator#21]

**Comment by ilix** [comment]
@martinloman nu ska den siffra på varje användare som anger antalet poster sättas vid importen. Petter t.ex. bör ha väldigt många och alla användare som startat en tråd bör ha minst en.

**Comment by martinloman** [comment]
Ja, när jag går in på profilen finns siffran där @ilix.
Däremot ser jag att feeden med "Den här användarens posts" är tom. Jag skapar en ny issue om det.

**Comment by martinloman** [comment]
Jag hittar några där antalet postningar diffar. T.ex. för moderatorn MikaelE som har 621 inlägg i gamla forumet och 484 i nya. Jag vet dock inte vad det beror på.

![image](https://cloud.githubusercontent.com/assets/1737278/21175704/f87e82aa-c1e3-11e6-9a81-dda17646fa1e.png)

**Comment by ilix** [comment]
@martinloman tack, får gräva lite mer i siffrorna!

**Comment by ilix** [comment]
Jag har läst in det hemliga admin-forumet nu och nu är MikaelEs antal 603 poster + 39 topics.

@martinloman du får kolla igen nästa gång testforumet uppdaterats.

**Comment by martinloman** [comment]
Det verkar inte stämma helt men bättre i alla fall. Lithium och NodeBB verkar ju överlag inte överens om hur många inlägg det finns.
