### ISSUE TITLE
Poster med HTML-innehåll verkar escapas

### ISSUE THREAD

**Issue by martinloman** [vimla-se/lithium-nodebb-migrator#34]
HTML source visas.

T.ex. Emma-Klaras fint formaterade postningar från förr, som denna:
https://nodebb.vimla.se/topic/287/hur-mycket-data-beh%C3%B6ver-jag

![image](https://cloud.githubusercontent.com/assets/1737278/21142196/46f89734-c141-11e6-9162-3d31c09ddeda.png)

**Comment by ilix** [comment]
De verkade följa ett mönster - wrappade i någon äcklig lithium-kod och html-encodat. Fixat lokalt och hamnar i test nästa gång.

**Comment by martinloman** [comment]
Fint @ilix !
