### ISSUE TITLE
Siffran _Views_ verkar inte migreras

### ISSUE THREAD

**Issue by martinloman** [vimla-se/lithium-nodebb-migrator#35]
Den är noll för alla poster.

**Comment by martinloman** [comment]
Ähh, fel projekt...

**Comment by ilix** [comment]
Hmm, vi har views i databasen men den siffran verkar knäpp. Gissar att den typats fel vid import från xml till mysql.

**Comment by ilix** [comment]
![screenshot from 2016-12-13 16-51-02](https://cloud.githubusercontent.com/assets/3116043/21147161/5c9d0e86-c154-11e6-8cd5-ecb5a2565efb.png)

**Comment by ilix** [comment]
@nisseds det här kom ej med i exporten från lithium (trasiga siffror).
