### ISSUE TITLE
User signatures are missing in posts

### ISSUE THREAD

**Issue by martinloman** [vimla-se/lithium-nodebb-migrator#37]
![image](https://cloud.githubusercontent.com/assets/1737278/21175408/79160764-c1e2-11e6-8548-3072c8e6e243.png)

**Comment by ilix** [comment]
People tend to use html in their signatures.

![screenshot from 2016-12-14 13-15-17](https://cloud.githubusercontent.com/assets/3116043/21181689/62f375da-c1ff-11e6-836d-bac1b5b0e4f0.png)

**Comment by ilix** [comment]
@martinloman fixed locally, you will see this the next time the migration has been run against the test forum.

**Comment by martinloman** [comment]
De finns med nu. Jag har ställt frågan till Rickard om det går att rendera html istället för att skriva ut den.

**Comment by ilix** [comment]
Frågan är om vi ska bearbeta innehållet något eller låta dem vara som de är.
