### ISSUE TITLE
The posts feed is empty on the user page

### ISSUE THREAD

**Issue by martinloman** [vimla-se/lithium-nodebb-migrator#38]
When opening a users page the feed of the users posts, to the right, is empty. For all users I think.

https://nodebb.vimla.se/user/mikaele

![image](https://cloud.githubusercontent.com/assets/1737278/21175762/44d1e714-c1e4-11e6-84c2-f5156d0645a2.png)

**Comment by ilix** [comment]
@martinloman på väg ut till testforumet

**Comment by martinloman** [comment]
Ser bra ut.
